# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gVHYIh7a4NbBIm_veHyPSselaqJANByt
"""

from google.colab import drive
drive.mount("/content/gdrive")

!nvidia-smi

!ls "/content/gdrive/My Drive/"

"""(1) Clone the DarkNet
https://www.youtube.com/watch?v=_FNfRtXEbr4&t=677s
"""

! git clone http://github.com/AlexeyAB/darknet

"""(2) Compile DarkNet using Nvidia GPU"""

# Commented out IPython magic to ensure Python compatibility.
#Change makefile to have GPU and OPENCV enabled
# %cd darknet
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!make

"""(3)Configure Darknet network for training YOLO v3"""

!cp cfg/yolov3.cfg cfg/yolov3_training.cfg

!sed -i 's/batch=1/batch=4/' cfg/yolov3_training.cfg
!sed -i 's/subdivisoions=1/subdivisions=16/' cfg/yolov3_training.cfg
!sed -i 's/max_batch=5000/max_batch=4000/' cfg/yolov3_training.cfg

!sed -i '610 s@classes=80@classes=1@' cfg/yolov3_training.cfg
!sed -i '696 s@classes=80@classes=1@' cfg/yolov3_training.cfg
!sed -i '783 s@classes=80@classes=1@' cfg/yolov3_training.cfg
!sed -i '603 s@classes=255@classes=18@' cfg/yolov3_training.cfg
!sed -i '689 s@classes=255@classes=18@' cfg/yolov3_training.cfg
!sed -i '776 s@classes=255@classes=18@' cfg/yolov3_training.cfg

#create folder on google drive to save the weight
!mkdir "/content/gdrive/My Drive/yolov3"

#Download weight from Darknet
!wget http://pjreddie.com/media/files/darknet53.conv.74

"""(4)Unzip our Dataset

"""

#Unzip the dataset from google drive
!apt install unzip
!unzip -uq "/content/gdrive/My Drive/HW2/train.zip" -d "/content/gdrive/My Drive/yolov3/Data"
!ls "/content/gdrive/My Drive/yolov3/"

import glob
images_list = glob.glob("/content/gdrive/My Drive/yolov3/Data/train/*.png")
print(images_list)

#Create training.txt file
file = open("/content/gdrive/My Drive/yolov3/Data/train.txt","w")
file.write("\n".join(images_list))
file.close()

#Start the training
! ./darknet detector train "/content/gdrive/My Drive/yolov3/Data/train" cfg/yolov3_training.cfg darknet53.conv.74 -dont show

!unzip -uq "/content/gdrive/My Drive/HW2/train.zip" -d "/content/gdrive/My Drive/HW2/Dataset"
!ls "/content/gdrive/My Drive/HW2/Dataset"

# Commented out IPython magic to ensure Python compatibility.
# install dependencies: (use cu101 because colab has CUDA 10.1)
!pip install -U torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html

# install mmcv-full thus we could use CUDA operators

!pip install mmcv-full==latest+torch1.6.0+cu101 -f https://download.openmmlab.com/mmcv/dist/index.html


# Install mmdetection
!rm -rf mmdetection
!git clone https://github.com/open-mmlab/mmdetection.git
# %cd mmdetection

!pip install -e .

# install Pillow 7.0.0 back in order to avoid bug in colab
!pip install Pillow==7.0.0